### ISSUE TITLE
Behaviour of Y is affected

### ISSUE THREAD

**Issue by shauryagoel** [mei28/luminate.nvim#23]
After enabling this plugin, Y yanks the complete line. However, after disabling this plugin Y yanks only the text after the cursor, which is the expected behaviour.

Neovim version: 0.10.1
luminate.nvim: d347e3997022ce96c695b919e3d0171e1ccea3d2

**Comment by mei28** [comment]
In my settings, regardless of whether my plugin is enabled or disabled, the Y behavior is the same as y$.

```lua
local illuminate = {
   "mei28/luminate.nvim",
  event = "VeryLazy",
  config = function()
    require 'luminate'.setup({
    })
  end,
}

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "--branch=stable", -- latest stable release
    lazyrepo,
    lazypath,
  }
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out,                            "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

-- Lazy plugin spec: https://github.com/folke/lazy.nvim#-plugin-spec
local lazy = require("lazy")
lazy.setup({ illuminate, }, {})

```

**Comment by shauryagoel** [comment]
I caught the issue with the following config in lazy.nvim-
```
{
  "mei28/luminate.nvim",
  keys = { "Y" },
  config = function()
    require("luminate").setup({ })
  end,
}


```

**Comment by mei28** [comment]
I used your settings and reproduced the problem. However, the issue is related to the lazy.nvim function. Therefore, even if you use keys = {'Y'} in another plugin, the problem may still occur

**Comment by shauryagoel** [comment]
Is the issue related to the "Y" key specifically? 
Is there another way to lazy load the plugin using key presses?

**Comment by mei28** [comment]
I used setting like follow, it works for me

```lua
  {
    'mei28/luminate.nvim',
    keys = { { 'u' }, { 'U' }, { '<C-r>' }, { 'p' }, { 'y' }, },
    config = function()
      require 'luminate'.setup({

      })
    end
  },
```

**Comment by mei28** [comment]
or it may works well as you want.

`  keys = { { 'Y', function() vim.cmd('normal! y$') end } },`

**Comment by shauryagoel** [comment]
Thank you that works!!!
