### ISSUE TITLE
`defer_clear_highlights`: invalid buffer id in `nvim_buf_clear_namespace` 

### ISSUE THREAD

**Issue by lttb** [mei28/luminate.nvim#4]
thanks for this plugin, looks really nice!

but I occasionally see this error:
```
Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/luminate.nvim/lua/luminate/init.lua:144: Invalid buffer id: 9
stack traceback:
	[C]: in function 'nvim_buf_clear_namespace'
	...ocal/share/nvim/lazy/luminate.nvim/lua/luminate/init.lua:144: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

it seems that it happens when I open the file with telescope.

video with an example of the issue:

https://github.com/mei28/luminate.nvim/assets/11135392/b8e51772-7514-4d93-a887-87b9480496cc

I'm happy to open a PR if I'll be able to resolve this issue.

thanks!

**Comment by mei28** [comment]
Thank you for reporting this issue. I will investigate to see if I can reproduce the problem.
