### ISSUE TITLE
Every newly typed word gets highlighted for a short time

### ISSUE THREAD

**Issue by shauryagoel** [mei28/luminate.nvim#5]
Hi, I am using the default config for the plugin with neovim v0.9.4. I am doing the following steps-
1) Open a new buffer and go into insert mode.
2) Type some text and go into normal mode.
3) Undo some text using `u`.
4) Go into insert mode and start typing something.

After step 4, typing the text keeps highlighting the newly typed characters for the `duration` time. Typing as done in step 2 produces no such highlights. I don't think this should happen as I am not doing any yanking, pasting, undoing or redoing, I am only typing some text in insert mode. If I disable this plugin, then above issue does not occur.

Moreover, instead of typing text as in step 2, if I paste some text from the system clipboard, I face the same issue.

Thanks!

**Comment by mei28** [comment]
Thank you for your report. I have identified the bugs you mentioned and confirmed that they originate from my plugin. Unfortunately, I am not sure how to fix them immediately.

(The bugs might be related to the on_bytes and TextChanged events.)

If you manage to fix these bugs, I would greatly appreciate a pull request!

**Comment by shauryagoel** [comment]
Unfortunately, I don't have enough expertise in neovim to open a PR. Hopefully, someone more experienced than me will be able to solve the issue.
